# Generated by Django 5.1.3 on 2024-11-18 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.FloatField(blank=True),
        ),
    ]
