# Generated by Django 5.1.3 on 2024-11-19 21:34

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('preferences', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('password', models.CharField(max_length=255)),
                ('bio', models.TextField()),
                ('joined_events', models.ManyToManyField(blank=True, related_name='participants', to='event.event')),
            ],
        ),
    ]
