# Generated by Django 5.1.3 on 2024-12-13 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friends+', to='user.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='incoming_requests',
            field=models.ManyToManyField(blank=True, related_name='incoming_requests+', to='user.user'),
        ),
    ]
